// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHotkey() {
  return window['go']['main']['App']['GetHotkey']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}
