// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHotkey():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function IsWindowVisible():Promise<boolean>;

export function RunTray():Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;
